'use client'

import { motion } from 'framer-motion'
import { ShieldCheck, Lock, EyeOff, Server, Key, Fingerprint, RefreshCw } from 'lucide-react'

export default function SecurityOverview() {
  const policies = [
    {
      icon: Fingerprint,
      title: "Imperceptible Cryptographic Watermarking",
      desc: "Every single audio file generated by VCaaS is embedded with an imperceptible, cryptographically signed watermark that survives heavy compression, filtering, and re-recording."
    },
    {
      icon: EyeOff,
      title: "Zero Data Retention",
      desc: "We do not store or use your audio uploads or inference prompts for model training. Voice clones are encrypted at rest and can be permanently purged instantly at your request."
    },
    {
      icon: ShieldCheck,
      title: "Consent Verification",
      desc: "To clone a voice, users must speak a dynamically generated consent phrase. This prevents non-consensual deepfakes of public figures or unconsenting individuals."
    },
    {
      icon: Server,
      title: "SOC 2 Type II Compliant",
      desc: "Our infrastructure is regularly audited by independent third-party security firms. Data is encrypted in transit (TLS 1.3) and at rest (AES-256)."
    }
  ]

  return (
    <div className="min-h-screen bg-[var(--bg)] text-[var(--text-1)] font-sans pb-24">
      {/* Hero */}
      <section className="pt-24 pb-16 px-6 relative overflow-hidden">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-[var(--accent)] opacity-5 blur-[120px] rounded-full pointer-events-none -z-10" />
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 mb-8">
            <Lock className="w-4 h-4 text-emerald-400" />
            <span className="text-xs font-medium text-emerald-400 tracking-wider uppercase">Enterprise Security</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-6">Security by Design</h1>
          <p className="text-[var(--text-2)] text-lg max-w-2xl mx-auto">
            We are building the future of generative audio, and we take the responsibility seriously. Our military-grade security architecture protects both our users and the public.
          </p>
        </div>
      </section>

      {/* Core Policies Grid */}
      <section className="max-w-6xl mx-auto px-6 grid grid-cols-1 md:grid-cols-2 gap-6 mb-24">
        {policies.map((policy, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: i * 0.1, duration: 0.5 }}
            className="bg-[var(--surface-1)] border border-[var(--border)] rounded-3xl p-8 hover:border-[var(--border-strong)] transition-colors"
          >
            <div className="w-12 h-12 bg-[var(--surface-2)] rounded-xl flex items-center justify-center mb-6">
              <policy.icon className="w-6 h-6 text-[var(--text-1)]" />
            </div>
            <h3 className="text-xl font-semibold mb-3">{policy.title}</h3>
            <p className="text-[var(--text-2)] leading-relaxed text-sm">{policy.desc}</p>
          </motion.div>
        ))}
      </section>

      {/* Trust Center Banner */}
      <section className="max-w-4xl mx-auto px-6">
        <div className="bg-gradient-to-r from-[var(--surface-2)] to-[var(--surface-1)] border border-[var(--border)] rounded-3xl p-10 flex flex-col md:flex-row items-center justify-between gap-8">
          <div>
            <h3 className="text-2xl font-bold mb-2">Security Audits & Reports</h3>
            <p className="text-[var(--text-2)] max-w-md">Download our latest penetration test results and compliance certifications.</p>
          </div>
          <button className="whitespace-nowrap px-8 py-4 bg-white text-black font-medium rounded-xl hover:bg-gray-200 transition-colors">
            Request Trust Pack
          </button>
        </div>
      </section>

    </div>
  )
}
