'use client'

import React from 'react'
import { motion } from 'framer-motion'
import { ShieldCheck, Lock, EyeOff, Server, Key, Fingerprint, RefreshCw, Zap } from 'lucide-react'

export default function SecurityOverview() {
  const policies = [
    {
      icon: Fingerprint,
      title: "Imperceptible Cryptographic Watermarking",
      desc: "Every single audio file generated by VCaaS is embedded with an imperceptible, cryptographically signed watermark that survives heavy compression, filtering, and re-recording."
    },
    {
      icon: EyeOff,
      title: "Zero Data Retention",
      desc: "We do not store or use your audio uploads or inference prompts for model training. Voice clones are encrypted at rest and can be permanently purged instantly at your request."
    },
    {
      icon: ShieldCheck,
      title: "Consent Verification",
      desc: "To clone a voice, users must speak a dynamically generated consent phrase. This prevents non-consensual deepfakes of public figures or unconsenting individuals."
    },
    {
      icon: Server,
      title: "SOC 2 Type II Compliant",
      desc: "Our infrastructure is regularly audited by independent third-party security firms. Data is encrypted in transit (TLS 1.3) and at rest (AES-256)."
    }
  ]

  return (
    <div className="min-h-screen bg-[var(--bg)] text-[var(--text-1)] font-sans pb-24">
      {/* Hero */}
      <section className="pt-24 pb-16 px-6 relative overflow-hidden">
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-[var(--accent)] opacity-5 blur-[120px] rounded-full pointer-events-none -z-10" />
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 mb-8">
            <Lock className="w-4 h-4 text-emerald-400" />
            <span className="text-xs font-medium text-emerald-400 tracking-wider uppercase">Enterprise Security</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-6">Security by Design</h1>
          <p className="text-[var(--text-2)] text-lg max-w-2xl mx-auto">
            We are building the future of generative audio, and we take the responsibility seriously. Our military-grade security architecture protects both our users and the public.
          </p>
        </div>
      </section>

      {/* Core Policies Grid */}
      <section className="max-w-6xl mx-auto px-6 grid grid-cols-1 md:grid-cols-2 gap-6 mb-24">
        {policies.map((policy, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: i * 0.1, duration: 0.5 }}
            className="bg-[var(--surface-1)] border border-[var(--border)] rounded-3xl p-8 hover:border-[var(--border-strong)] transition-colors"
          >
            <div className="w-12 h-12 bg-[var(--surface-2)] rounded-xl flex items-center justify-center mb-6">
              <policy.icon className="w-6 h-6 text-[var(--text-1)]" />
            </div>
            <h3 className="text-xl font-semibold mb-3">{policy.title}</h3>
            <p className="text-[var(--text-2)] leading-relaxed text-sm">{policy.desc}</p>
          </motion.div>
        ))}
      </section>

      {/* 6-Layer Verification Tool */}
      <section className="max-w-4xl mx-auto px-6 mb-24">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.2 }}
          className="bg-[var(--surface-1)] border-t-4 border border-[var(--border)] rounded-3xl p-8"
          style={{ borderTopColor: 'var(--accent)' }}
        >
          <div className="flex items-center gap-3 mb-6">
            <Zap className="h-6 w-6 text-[var(--accent)]" />
            <h2 className="text-2xl font-bold text-[var(--text-1)]">6-Layer Deepfake Analysis</h2>
          </div>
          <p className="text-[var(--text-2)] mb-8 text-sm max-w-2xl">
            Upload any audio clip to run it through our military-grade defense mechanism. We analyze acoustics, prosody, paralinguistics, semantics, and verify cryptographic watermarks in real-time.
          </p>

          <DeepfakeAnalyzer />
        </motion.div>
      </section>

      {/* Trust Center Banner */}
      <section className="max-w-4xl mx-auto px-6">
        <div className="bg-gradient-to-r from-[var(--surface-2)] to-[var(--surface-1)] border border-[var(--border)] rounded-3xl p-10 flex flex-col md:flex-row items-center justify-between gap-8">
          <div>
            <h3 className="text-2xl font-bold mb-2">Security Audits & Reports</h3>
            <p className="text-[var(--text-2)] max-w-md">Download our latest penetration test results and compliance certifications.</p>
          </div>
          <button className="whitespace-nowrap px-8 py-4 bg-white text-black font-medium rounded-xl hover:bg-gray-200 transition-colors">
            Request Trust Pack
          </button>
        </div>
      </section>

    </div>
  )
}

function DeepfakeAnalyzer() {
  const [file, setFile] = React.useState<File | null>(null)
  const [loading, setLoading] = React.useState(false)
  const [result, setResult] = React.useState<any>(null)
  const [error, setError] = React.useState<string | null>(null)

  const handleVerify = async () => {
    if (!file) return
    setLoading(true)
    setError(null)
    setResult(null)
    try {
      const { verifyAudio } = await import('@/lib/api')
      const res = await verifyAudio(file)
      setResult(res)
    } catch (err: any) {
      setError(err.message || 'Verification failed. Ensure you are logged in as a premium user.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row items-center gap-4">
        <input 
          type="file" 
          accept="audio/*" 
          onChange={e => setFile(e.target.files?.[0] || null)}
          className="block w-full max-w-sm text-sm text-[var(--text-2)]
            file:mr-4 file:py-3 file:px-5
            file:rounded-xl file:border-0
            file:text-sm file:font-semibold
            file:bg-[var(--surface-2)] file:text-[var(--text-1)]
            hover:file:bg-[var(--surface-3)] transition-colors cursor-pointer"
        />
        <button 
          onClick={handleVerify}
          disabled={!file || loading}
          className="bg-white text-black font-medium px-8 py-3 rounded-xl hover:bg-gray-200 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {loading ? 'Analyzing...' : 'Run Analysis'}
        </button>
      </div>

      {error && (
        <div className="p-4 bg-red-500/10 border border-red-500/20 text-red-400 rounded-xl text-sm">
          {error}
        </div>
      )}

      {result && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-8">
          <div className="col-span-full mb-4">
            <h3 className="text-xl font-bold text-[var(--text-1)] flex items-center gap-2 mb-2">
              Final Decision: 
              <span className={`tracking-wider ${result.verdict?.includes('Human') ? 'text-emerald-400' : result.verdict?.includes('Watermarked') ? 'text-[#3b82f6]' : 'text-red-400'}`}>
                {result.verdict}
              </span>
            </h3>
            <div className="inline-block px-3 py-1 bg-[var(--surface-2)] rounded-lg text-sm font-medium text-[var(--text-2)] border border-[var(--border)]">
              Overall Authenticity: {((result.overall_authenticity_score || 0) * 100).toFixed(1)}%
            </div>
          </div>

          <LayerCard title="1. Anti-Spoof (Acoustics)" data={result.layers?.layer1_antispoof} scoreField="spoof_score" invert />
          <LayerCard title="2. Speaker Identity" data={result.layers?.layer2_speaker} scoreField="similarity_score" />
          <LayerCard title="3. Prosody (Pitch Stability)" data={result.layers?.layer3_prosody} scoreField="authenticity_score" />
          <LayerCard title="4. Paralinguistic (Emotion)" data={result.layers?.layer4_paralinguistic} scoreField="authenticity_score" />
          <LayerCard title="5. Semantic (Whisper)" data={result.layers?.layer5_semantic} scoreField="authenticity_score" />
          <div className="bg-[var(--surface-2)] p-5 rounded-xl border border-[var(--border)] flex flex-col justify-center">
            <h4 className="text-sm font-medium text-[var(--text-2)] mb-3">6. Watermark Detection</h4>
            <div className={`text-2xl font-bold ${result.layers?.layer6_watermark?.found ? 'text-[#3b82f6]' : 'text-[var(--text-3)]'}`}>
              {result.layers?.layer6_watermark?.found ? 'DETECTED' : 'Not Found'}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

function LayerCard({ title, data, scoreField, invert = false }: { title: string, data: any, scoreField: string, invert?: boolean }) {
  if (!data || data.status === 'skipped') {
    return (
      <div className="bg-[var(--surface-2)] p-5 rounded-xl border-l-4 border-[var(--border)] border-l-[var(--text-3)]">
        <h4 className="text-sm font-medium text-[var(--text-2)] mb-2">{title}</h4>
        <div className="text-xl font-bold text-[var(--text-3)]">Skipped</div>
      </div>
    )
  }
  if (data.error) {
    return (
      <div className="bg-[var(--surface-2)] p-5 rounded-xl border-l-4 border-[var(--border)] border-l-yellow-500">
        <h4 className="text-sm font-medium text-[var(--text-2)] mb-2">{title}</h4>
        <div className="text-sm text-yellow-500 mb-2">Error</div>
        <div className="text-xs text-[var(--text-3)] overflow-auto max-h-24">
          {data.error}
        </div>
      </div>
    )
  }
  const score = data[scoreField] || 0;
  const displayScore = invert ? (1 - score) : score;
  const isSuspicious = displayScore < 0.5;

  return (
    <div className={`bg-[var(--surface-2)] p-5 rounded-xl border-l-4 border-[var(--border)] ${isSuspicious ? 'border-l-red-500' : 'border-l-emerald-500'}`}>
      <h4 className="text-sm font-medium text-[var(--text-2)] mb-2">{title}</h4>
      <div className="text-xl font-bold text-[var(--text-1)] mb-3">Score: {(score * 100).toFixed(1)}%</div>
      <div className="text-xs text-[var(--text-3)] font-mono overflow-auto max-h-24 bg-[var(--surface-1)] p-2 rounded">
        {JSON.stringify(data.details || data.features || data, null, 2)}
      </div>
    </div>
  )
}
