"""
Prosody & Emotion Coherence Service — Layer 3 of the 6-layer defense pipeline.

Analyses pitch (F0) stability and rhythm patterns in a speech recording.
Synthetic voices generated by current TTS systems tend to exhibit unnaturally
consistent F0 trajectories (no micro-variation, no breath pauses, no
speaker-specific jitter), which this module quantifies.

IMPLEMENTATION:
  - F0 extraction via librosa.pyin (probabilistic YIN)
  - Pitch stability metrics: std/mean coefficient of variation (CV)
  - Voiced-frame ratio (synthetic audio is often fully voiced)
  - Returns an authenticity_score in [0, 1] where 1 = natural-sounding.

LIMITATIONS / TODO:
  - Layer 4 (Paralinguistic / Emotion): requires a speech-emotion recognition
    (SER) model (e.g. wav2vec2-based) to compare emotional valence of the
    audio against sentiment of the text. Not yet implemented.
  - Replace the simple CV threshold with a learned classifier trained on
    natural vs. XTTS / ElevenLabs / Bark output distributions.
"""
from __future__ import annotations

from typing import Any, Dict

import librosa
import numpy as np


class ProsodyService:
    """Layer 3: Prosody & Emotion Coherence analyser."""

    # F0 extraction parameters
    _FMIN = librosa.note_to_hz("C2")   # ~65 Hz — lowest plausible F0
    _FMAX = librosa.note_to_hz("C7")   # ~2093 Hz — highest plausible F0
    _FRAME_LENGTH = 2048
    _HOP_LENGTH = 512

    # Authenticity thresholds (tuned empirically; treat as starting-point)
    _CV_NATURAL_MAX = 0.35   # natural speech F0 CV is typically 0.15–0.35
    _VOICED_RATIO_MAX = 0.92  # fully voiced = suspicious

    def analyse(self, audio_path: str) -> Dict[str, Any]:
        """Run prosody analysis on an audio file.

        Args:
            audio_path: Path to a WAV/FLAC/MP3 file.

        Returns:
            Dict with:
              - authenticity_score (float, 0–1, higher = more natural)
              - pitch_stability_cv  (float, coefficient of variation of F0)
              - f0_mean_hz          (float)
              - f0_std_hz           (float)
              - voiced_frame_ratio  (float)
              - engine              (str)
              - details             (dict of raw values)
        """
        try:
            y, sr = librosa.load(audio_path, sr=16000, mono=True)
            return self._analyse_waveform(y, sr)
        except Exception as exc:
            return {
                "authenticity_score": 0.5,  # unknown / neutral when analysis fails
                "error": str(exc),
                "engine": "prosody_heuristic",
            }

    def _analyse_waveform(self, y: np.ndarray, sr: int) -> Dict[str, Any]:
        # Extract F0 with pyin (probabilistic YIN — more robust than plain YIN)
        f0, voiced_flag, voiced_probs = librosa.pyin(
            y,
            fmin=self._FMIN,
            fmax=self._FMAX,
            sr=sr,
            frame_length=self._FRAME_LENGTH,
            hop_length=self._HOP_LENGTH,
        )

        # Mask out unvoiced frames
        voiced_f0 = f0[voiced_flag]

        voiced_frame_ratio = float(voiced_flag.sum() / max(len(voiced_flag), 1))

        if len(voiced_f0) < 5:
            # Not enough voiced speech to draw conclusions
            return {
                "authenticity_score": 0.5,
                "f0_mean_hz": None,
                "f0_std_hz": None,
                "pitch_stability_cv": None,
                "voiced_frame_ratio": voiced_frame_ratio,
                "engine": "prosody_heuristic",
                "details": {"note": "Insufficient voiced frames for F0 analysis"},
            }

        f0_mean = float(np.nanmean(voiced_f0))
        f0_std = float(np.nanstd(voiced_f0))
        cv = f0_std / (f0_mean + 1e-6)  # coefficient of variation

        # Score components (each in [0, 1], higher = more authentic):
        #   1. Pitch variation: natural speech has moderate CV; too low = synthetic
        cv_score = float(np.clip(cv / self._CV_NATURAL_MAX, 0.0, 1.0))

        #   2. Voiced-frame ratio: synthetic TTS often produces fully voiced audio
        voiced_score = float(
            np.clip(1.0 - ((voiced_frame_ratio - self._VOICED_RATIO_MAX) / (1.0 - self._VOICED_RATIO_MAX + 1e-6)), 0.0, 1.0)
            if voiced_frame_ratio > self._VOICED_RATIO_MAX
            else 1.0
        )

        # Weighted combination
        authenticity_score = float(0.6 * cv_score + 0.4 * voiced_score)

        return {
            "authenticity_score": round(authenticity_score, 4),
            "f0_mean_hz": round(f0_mean, 2),
            "f0_std_hz": round(f0_std, 2),
            "pitch_stability_cv": round(cv, 4),
            "voiced_frame_ratio": round(voiced_frame_ratio, 4),
            "engine": "prosody_heuristic",
            "details": {
                "cv_score": round(cv_score, 4),
                "voiced_score": round(voiced_score, 4),
                "total_frames": len(f0),
                "voiced_frames": int(voiced_flag.sum()),
            },
        }
