export default function TermsPage() {
  return (
    <div className="min-h-screen py-24 px-6 max-w-4xl mx-auto text-[var(--text-1)]">
      <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
      <div className="space-y-8 text-[var(--text-2)] leading-relaxed">
        <p className="text-sm opacity-70">Last updated: August 2026</p>
        
        <section>
          <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
          <p>By accessing and using VCaaS ("the Platform"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use our service.</p>
        </section>
        
        <section>
          <h2 className="text-2xl font-semibold text-white mb-4">2. Description of Service</h2>
          <p>VCaaS provides an API and web interface for zero-shot voice cloning, text-to-speech generation, and deepfake verification. The platform utilizes advanced machine learning models (including XTTS v2) and proprietary cryptographic audio watermarking to synthesize and verify speech.</p>
        </section>
        
        <section>
          <h2 className="text-2xl font-semibold text-white mb-4">3. Strict Acceptable Use Policy</h2>
          <p className="mb-4">As a user of VCaaS, you are strictly prohibited from using the platform to:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Clone the voice of any individual (living or deceased) without their explicit, written, and revocable consent.</li>
            <li>Generate audio intended to deceive, defraud, or impersonate individuals or organizations.</li>
            <li>Produce hate speech, harassment, defamatory content, or content that incites violence.</li>
            <li>Bypass, tamper with, or attempt to remove the cryptographic acoustic watermark embedded in all generated audio.</li>
            <li>Use the platform to create political misinformation or deepfakes for political campaigns.</li>
          </ul>
          <p className="mt-4">Violation of these terms will result in immediate account termination, deletion of all associated models, and potential reporting to relevant authorities.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white mb-4">4. Cryptographic Watermarking & Verification</h2>
          <p>To promote ethical AI use, <strong>all audio generated by VCaaS is permanently embedded with a high-frequency (19kHz) cryptographic watermark</strong> containing a signed payload. You acknowledge that any audio you generate can be mathematically proven to have originated from this platform. By using this service, you consent to this watermarking process.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white mb-4">5. Intellectual Property & Ownership</h2>
          <p className="mb-4"><strong>Your Content:</strong> You retain ownership of any reference audio you upload, provided you have the legal right to possess and use it. You grant VCaaS a temporary license to process this audio solely for generating your requested text-to-speech outputs.</p>
          <p><strong>Generated Audio:</strong> You own the rights to the synthesized audio generated by your prompts, subject to your compliance with the Acceptable Use Policy. Commercial usage is permitted only under the appropriate paid tier.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white mb-4">6. API Usage & Rate Limiting</h2>
          <p>If accessing VCaaS via our REST API, you agree to secure your authentication tokens. You are responsible for all activity occurring under your API keys. We reserve the right to enforce rate limits and suspend access if we detect abusive, high-volume polling, or circumvention of usage limits.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white mb-4">7. Limitation of Liability</h2>
          <p>VCaaS is provided "as is" without warranties of any kind. We shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the platform, the inability to use the platform, or any unauthorized access to your data.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white mb-4">8. Modifications to Terms</h2>
          <p>We reserve the right to modify these terms at any time. We will notify users of significant changes via the email address associated with their account. Continued use of the platform after changes constitutes acceptance of the new terms.</p>
        </section>
      </div>
    </div>
  )
}
